# Site settings
title: "OSBA: Open Service Broker for Azure"
email: ""
description: > # this means to ignore newlines until "baseurl:"
  OSBA: Open Service Broker for Azure
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://osba.sh" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [docs, vendor, script, node_modules, Gruntfile.js, Gemfile, Gemfile.lock, package.json, s3_website.yml, gulpfile.js, README.md, Makefile]
